services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: djblog
    command: gunicorn blog_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
    ports:
      - "80:80"
    restart: always
